import React, { createContext, useContext, useState, useEffect } from "react";
import { LanguageCode } from "../types";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "zh", name: "Chinese (Simplified)", nativeName: "简体中文", flag: "🇨🇳" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦" },
];

export const translations: Record<string, Record<string, string>> = {
  // Navigation
  "nav.home": {
    en: "Home",
    es: "Inicio",
    fr: "Accueil",
    de: "Startseite",
    zh: "首页",
    hi: "होम",
    ar: "الرئيسية",
    pt: "Início",
    ja: "ホーム",
    ru: "Главная",
    ko: "홈",
    it: "Home",
    nl: "Home",
    tr: "Ana Sayfa",
    id: "Beranda",
    te: "హోమ్",
    ta: "முகப்பு",
    bn: "হোম",
    mr: "मुख्यपृष्ठ",
    vi: "Trang chủ",
    pl: "Strona główna",
    uk: "Головна",
  },
  "nav.findJobs": {
    en: "Find Jobs",
    es: "Buscar Empleos",
    fr: "Trouver des Emplois",
    de: "Jobs finden",
    zh: "职位搜索",
    hi: "नौकरियां खोजें",
    ar: "البحث عن وظائف",
    pt: "Buscar Vagas",
    ja: "仕事を探す",
    ru: "Поиск работы",
    ko: "일자리 찾기",
    it: "Cerca Lavoro",
    nl: "Vacatures zoeken",
    tr: "İş Bul",
    id: "Cari Lowongan",
    te: "ఉద్యోగాలు వెతకండి",
    ta: "வேலை தேடுங்கள்",
    bn: "চাকরি খুঁজুন",
    mr: "नोकऱ्या शोधा",
    vi: "Tìm việc làm",
    pl: "Szukaj pracy",
    uk: "Знайти роботу",
  },
  "nav.postJob": {
    en: "Post a Job",
    es: "Publicar Empleo",
    fr: "Publier une Offre",
    de: "Job inserieren",
    zh: "发布职位",
    hi: "नौकरी पोस्ट करें",
    ar: "نشر وظيفة",
    pt: "Publicar Vaga",
    ja: "求人を掲載",
    ru: "Разместить вакансию",
    ko: "채용 공고 등록",
    it: "Pubblica Offerta",
    nl: "Vacature plaatsen",
    tr: "İş İlanı Ver",
    id: "Pasang Lowongan",
    te: "ఉద్యోగాన్ని పోస్ట్ చేయండి",
    ta: "வேலை வாய்ப்பு பதிவிடுங்கள்",
    bn: "চাকরি পোস্ট করুন",
    mr: "नोकरी पोस्ट करा",
    vi: "Đăng tin tuyển dụng",
    pl: "Opublikuj ofertę",
    uk: "Опублікувати вакансію",
  },
  "nav.dashboard": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    zh: "控制面板",
    hi: "डैशबोर्ड",
    ar: "لوحة التحكم",
    pt: "Painel",
    ja: "ダッシュボード",
    ru: "Панель",
    ko: "대시보드",
    it: "Dashboard",
    nl: "Dashboard",
    tr: "Gösterge Paneli",
    id: "Dasbor",
    te: "డాష్‌బోర్డ్",
    ta: "டாஷ்போர்டு",
    bn: "ড্যাশবোর্ড",
    mr: "डॅशबोर्ड",
    vi: "Bảng điều khiển",
    pl: "Panel",
    uk: "Панель",
  },
  "nav.jobAlerts": {
    en: "Job Alerts",
    es: "Alertas de Empleo",
    fr: "Alertes d'Emploi",
    de: "Job-Alerts",
    zh: "职位提醒",
    hi: "जॉब अलर्ट",
    ar: "تنبيهات الوظائف",
    pt: "Alertas de Vagas",
    ja: "ジョブアラート",
    ru: "Оповещения о работе",
    ko: "채용 알림",
    it: "Avvisi di Lavoro",
    nl: "Job alerts",
    tr: "İş Uyarıları",
    id: "Peringatan Lowongan",
    te: "ఉద్యోగ హెచ్చరికలు",
    ta: "வேலை விழிப்பூட்டல்கள்",
    bn: "চাকরি সতর্কতা",
    mr: "जॉब अलर्ट्स",
    vi: "Thông báo việc làm",
    pl: "Powiadomienia o pracy",
    uk: "Оповіщення про роботу",
  },
  "nav.messages": {
    en: "Messages & AI",
    es: "Mensajes e IA",
    fr: "Messages & IA",
    de: "Nachrichten & KI",
    zh: "消息与AI",
    hi: "संदेश और एआई",
    ar: "الرسائل والذكاء الاصطناعي",
    pt: "Mensagens & IA",
    ja: "メッセージ & AI",
    ru: "Сообщения и ИИ",
    ko: "메시지 및 AI",
    it: "Messaggi e IA",
    nl: "Berichten & AI",
    tr: "Mesajlar ve Yapay Zekâ",
    id: "Pesan & AI",
    te: "సందేశాలు & AI",
    ta: "செய்திகள் & AI",
    bn: "বার্তা ও এআই",
    mr: "संदेश आणि एआय",
    vi: "Tin nhắn & AI",
    pl: "Wiadomości i AI",
    uk: "Повідомлення та ШІ",
  },
  "nav.resume": {
    en: "Resume & CV",
    es: "Currículum y CV",
    fr: "CV & Résumé",
    de: "Lebenslauf & CV",
    zh: "简历与CV",
    hi: "रिज्यूमे और सीवी",
    ar: "السيرة الذاتية",
    pt: "Currículo & CV",
    ja: "履歴書 & CV",
    ru: "Резюме и CV",
    ko: "이력서 & CV",
    it: "Curriculum e CV",
    nl: "CV & Resumé",
    tr: "Özgeçmiş & CV",
    id: "Resume & CV",
    te: "రెజ్యూమ్ & CV",
    ta: "ரெஸ்யூம் & CV",
    bn: "জীবনবৃত্তান্ত ও সিভি",
    mr: "रेझ्युमे व सीव्ही",
    vi: "Hồ sơ & CV",
    pl: "CV i życiorys",
    uk: "Резюме та CV",
  },
  "nav.profile": {
    en: "Profile",
    es: "Perfil",
    fr: "Profil",
    de: "Profil",
    zh: "个人中心",
    hi: "प्रोफाइल",
    ar: "الملف الشخصي",
    pt: "Perfil",
    ja: "プロフィール",
    ru: "Профиль",
    ko: "프로필",
    it: "Profilo",
    nl: "Profiel",
    tr: "Profil",
    id: "Profil",
    te: "ప్రొఫైల్",
    ta: "சுயவிவரம்",
    bn: "প্রোফাইল",
    mr: "प्रोफाइल",
    vi: "Hồ sơ",
    pl: "Profil",
    uk: "Профіль",
  },
  "nav.settings": {
    en: "Settings",
    es: "Configuración",
    fr: "Paramètres",
    de: "Einstellungen",
    zh: "设置",
    hi: "सेटिंग्स",
    ar: "الإعدادات",
    pt: "Configurações",
    ja: "設定",
    ru: "Настройки",
    ko: "설정",
    it: "Impostazioni",
    nl: "Instellingen",
    tr: "Ayarlar",
    id: "Pengaturan",
    te: "సెట్టింగులు",
    ta: "அமைப்புகள்",
    bn: "সেটিংস",
    mr: "सेटिंग्ज",
    vi: "Cài đặt",
    pl: "Ustawienia",
    uk: "Налаштування",
  },
  "nav.login": {
    en: "Login",
    es: "Iniciar Sesión",
    fr: "Connexion",
    de: "Anmelden",
    zh: "登录",
    hi: "लॉग इन",
    ar: "تسجيل الدخول",
    pt: "Entrar",
    ja: "ログイン",
    ru: "Войти",
    ko: "로그인",
    it: "Accedi",
    nl: "Inloggen",
    tr: "Giriş Yap",
    id: "Masuk",
    te: "లాగిన్",
    ta: "உள்நுழைக",
    bn: "লগইন",
    mr: "लॉगिन",
    vi: "Đăng nhập",
    pl: "Zaloguj się",
    uk: "Увійти",
  },
  "nav.logout": {
    en: "Logout",
    es: "Cerrar Sesión",
    fr: "Déconnexion",
    de: "Abmelden",
    zh: "登出",
    hi: "लॉग आउट",
    ar: "تسجيل الخروج",
    pt: "Sair",
    ja: "ログアウト",
    ru: "Выйти",
    ko: "로그아웃",
    it: "Esci",
    nl: "Uitloggen",
    tr: "Çıkış Yap",
    id: "Keluar",
    te: "లాగ్ అవుట్",
    ta: "வெளியேறு",
    bn: "লগআউট",
    mr: "लॉग आउट",
    vi: "Đăng xuất",
    pl: "Wyloguj się",
    uk: "Вийти",
  },
  "nav.searchPlaceholder": {
    en: "Search jobs, roles, skills...",
    es: "Buscar empleos, puestos, habilidades...",
    fr: "Rechercher des emplois, postes, compétences...",
    de: "Jobs, Rollen, Fähigkeiten suchen...",
    zh: "搜索职位、工种、技能...",
    hi: "नौकरियां, पद, कौशल खोजें...",
    ar: "ابحث عن الوظائف والأدوار والمهارات...",
    pt: "Buscar vagas, cargos, habilidades...",
    ja: "求人、職種、スキルを検索...",
    ru: "Поиск вакансий, ролей, навыков...",
    ko: "채용, 직무, 기술 검색...",
    it: "Cerca offerte, ruoli, competenze...",
    nl: "Zoek vacatures, rollen, vaardigheden...",
    tr: "İş, unvan, yetenek ara...",
    id: "Cari lowongan, peran, keahlian...",
    te: "ఉద్యోగాలు, పాత్రలు, నైపుణ్యాలను వెతకండి...",
    ta: "வேலைகள், பாத்திரங்கள், திறன்களைத் தேடுங்கள்...",
    bn: "চাকরি, ভূমিকা, দক্ষতা অনুসন্ধান করুন...",
    mr: "नोकऱ्या, भूमिका, कौशल्ये शोधा...",
    vi: "Tìm việc làm, vị trí, kỹ năng...",
    pl: "Szukaj ofert, ról, umiejętności...",
    uk: "Пошук роботи, посад, навичок...",
  },
  "nav.notifications": {
    en: "Notifications",
    es: "Notificaciones",
    fr: "Notifications",
    de: "Benachrichtigungen",
    zh: "通知",
    hi: "सूचनाएं",
    ar: "الإشعارات",
    pt: "Notificações",
    ja: "通知",
    ru: "Уведомления",
    ko: "알림",
    it: "Notifiche",
    nl: "Meldingen",
    tr: "Bildirimler",
    id: "Notifikasi",
    te: "నోటిఫికేషన్‌లు",
    ta: "அறிவிப்புகள்",
    bn: "বিজ্ঞপ্তি",
    mr: "सूचना",
    vi: "Thông báo",
    pl: "Powiadomienia",
    uk: "Сповіщення",
  },
  "nav.language": {
    en: "Language",
    es: "Idioma",
    fr: "Langue",
    de: "Sprache",
    zh: "语言",
    hi: "भाषा",
    ar: "اللغة",
    pt: "Idioma",
    ja: "言語",
    ru: "Язык",
    ko: "언어",
    it: "Lingua",
    nl: "Taal",
    tr: "Dil",
    id: "Bahasa",
    te: "భాష",
    ta: "மொழி",
    bn: "ভাষা",
    mr: "भाषा",
    vi: "Ngôn ngữ",
    pl: "Język",
    uk: "Мова",
  },
  "alerts.title": {
    en: "Job Alerts",
    es: "Alertas de Empleo",
    fr: "Alertes d'Emploi",
    de: "Job-Benachrichtigungen",
    zh: "职位提醒",
    hi: "जॉब अलर्ट",
    ar: "تنبيهات الوظائف",
    pt: "Alertas de Emprego",
    ja: "求人アラート",
    ru: "Оповещения о вакансиях",
    ko: "채용 알림",
    it: "Avvisi di Lavoro",
    nl: "Vacature alerts",
    tr: "İş Uyarıları",
    id: "Peringatan Lowongan",
    te: "ఉద్యోగ హెచ్చరికలు",
    ta: "வேலை அறிவிப்புகள்",
    bn: "কাজের সতর্কতা",
    mr: "नोकरी सूचना",
    vi: "Thông báo việc làm",
    pl: "Powiadomienia o pracy",
    uk: "Сповіщення про роботу",
  },
  "alerts.realCompanyNotice": {
    en: "All job alerts are delivered strictly when genuine, verified companies publish matching opportunities.",
    es: "Todas las alertas se envían estrictamente cuando empresas reales y verificadas publican ofertas.",
    fr: "Toutes les alertes sont délivrées uniquement lorsque de véritables entreprises vérifiées publient des offres.",
    de: "Alle Job-Alerts werden ausschließlich versendet, wenn echte, verifizierte Unternehmen Angebote veröffentlichen.",
    zh: "所有职位提醒均在真实、经过验证的企业发布匹配职位时精准推送。",
    hi: "सभी जॉब अलर्ट वास्तविक और सत्यापित कंपनियों द्वारा नई नौकरी पोस्ट करने पर ही भेजे जाते हैं।",
    ar: "يتم إرسال جميع تنبيهات الوظائف فقط عندما تنشر شركات حقيقية ومعتمدة فرص عمل مطابقة.",
    pt: "Todos os alertas são enviados estritamente quando empresas reais e verificadas publicam vagas.",
    ja: "すべての求人アラートは、実在する検証済み企業が条件に合う求人を掲載した際にのみ届きます。",
    ru: "Все оповещения о вакансиях приходят исключительно при публикации реальными компаниями.",
    ko: "모든 채용 알림은 검증된 실제 기업이 채용 공고를 게시할 때만 발송됩니다.",
    it: "Tutti gli avvisi di lavoro vengono inviati solo quando aziende reali e verificate pubblicano offerte.",
    nl: "Alle vacaturemeldingen worden alleen verstuurd wanneer echte, geverifieerde bedrijven vacatures plaatsen.",
    tr: "Tüm iş uyarıları yalnızca gerçek ve onaylı şirketler ilan yayınladığında gönderilir.",
    id: "Semua peringatan lowongan hanya dikirimkan ketika perusahaan nyata dan terverifikasi memasang lowongan.",
    te: "నిజమైన మరియు ధృవీకరించబడిన కంపెనీలు సరిపోలే ఉద్యోగాలను పోస్ట్ చేసినప్పుడు మాత్రమే హెచ్చరికలు అందుతాయి.",
    ta: "உண்மையான மற்றும் சரிபார்க்கப்பட்ட நிறுவனங்கள் வேலைகளை இடும் போது மட்டுமே அறிவிப்புகள் அனுப்பப்படும்.",
    bn: "সমস্ত চাকরির সতর্কতা শুধুমাত্র আসল ও যাচাইকৃত কোম্পানি পদ পোস্ট করলেই পাঠানো হয়।",
    mr: "सर्व जॉब अलर्ट्स केवळ वास्तविक आणि पडताळणी केलेल्या कंपन्यांनी संधी पोस्ट केल्यावरच पाठवले जातात.",
    vi: "Tất cả thông báo việc làm chỉ được gửi khi các công ty thực sự và đã xác minh đăng tin tuyển dụng.",
    pl: "Wszystkie powiadomienia są wysyłane wyłącznie wtedy, gdy prawdziwe firmy publikują oferty.",
    uk: "Усі сповіщення про роботу надсилаються виключно тоді, коли реальні перевірені компанії публікують вакансії.",
  },
  "alerts.noAlerts": {
    en: "No active job alerts. Set up your preferences below to be notified when real employers post jobs.",
    es: "Sin alertas activas. Configura tus preferencias abajo para recibir avisos cuando empresas reales publiquen.",
    fr: "Aucune alerte active. Configurez vos préférences ci-dessous pour être notifié des offres réelles.",
    de: "Keine aktiven Alerts. Richten Sie Ihre Kriterien ein, um von echten Arbeitgebern benachrichtigt zu werden.",
    zh: "暂无有效职位提醒。在下方设置偏好，以便在真实雇主发布职位时收到通知。",
    hi: "कोई सक्रिय अलर्ट नहीं है। वास्तविक नियोक्ताओं द्वारा पोस्ट किए जाने पर सूचना पाने के लिए अपनी प्राथमिकताएं सेट करें।",
    ar: "لا توجد تنبيهات نشطة. قم بإعداد تفضيلاتك لتلقي إشعارات عندما تنشر الشركات الحقيقية وظائف.",
    pt: "Nenhum alerta ativo. Defina suas preferências abaixo para ser notificado sobre vagas reais.",
    ja: "有効な求人アラートはありません。実際の企業が求人を掲載した際に通知を受け取るには設定してください。",
    ru: "Нет активных оповещений. Настройте критерии, чтобы получать уведомления от реальных работодателей.",
    ko: "활성 채용 알림이 없습니다. 실제 기업이 채용 공고를 올릴 때 알림을 받도록 설정하세요.",
    it: "Nessun avviso attivo. Imposta le tue preferenze qui sotto per ricevere notifiche su offerte reali.",
    nl: "Geen actieve meldingen. Stel uw voorkeuren in om meldingen te ontvangen van echte werkgevers.",
    tr: "Aktif iş uyarısı yok. Gerçek işverenler ilan verdiğinde bildirim almak için tercihlerinizi belirleyin.",
    id: "Tidak ada peringatan aktif. Atur preferensi Anda agar diberi tahu saat perusahaan asli memasang lowongan.",
    te: "క్రియాశీల హెచ్చరికలు లేవు. నిజమైన యజమానులు ఉద్యోగాలు పోస్ట్ చేసినప్పుడు తెలియజేయబడటానికి ప్రాధాన్యతలను సెట్ చేయండి.",
    ta: "செயலில் உள்ள விழிப்பூட்டல்கள் இல்லை. உண்மையான முதலாளிகள் வேலைகளை இடும்போது அறிவிக்கப்பட விருப்பங்களை அமைக்கவும்.",
    bn: "কোন সক্রিয় কাজের সতর্কতা নেই। প্রকৃত নিয়োগকর্তারা চাকরি পোস্ট করলে বিজ্ঞপ্তি পেতে পছন্দ সেট করুন।",
    mr: "सक्रिय अलर्ट नाहीत. वास्तविक नियोक्त्यांनी नोकऱ्या पोस्ट केल्यावर सूचना मिळवण्यासाठी प्राधान्ये सेट करा.",
    vi: "Không có thông báo nào đang hoạt động. Hãy thiết lập tiêu chí để nhận thông báo từ nhà tuyển dụng thực sự.",
    pl: "Brak aktywnych powiadomień. Ustaw preferencje, aby otrzymywać powiadomienia o prawdziwych ofertach.",
    uk: "Немає активних сповіщень. Налаштуйте критерії, щоб отримувати сповіщення від реальних роботодавців.",
  },
  "alerts.createBtn": {
    en: "Create New Alert",
    es: "Crear Nueva Alerta",
    fr: "Créer une Alerte",
    de: "Neuen Alert erstellen",
    zh: "创建新提醒",
    hi: "नया अलर्ट बनाएं",
    ar: "إنشاء تنبيه جديد",
    pt: "Criar Novo Alerta",
    ja: "新しいアラートを作成",
    ru: "Создать оповещение",
    ko: "새 알림 만들기",
    it: "Crea Nuovo Avviso",
    nl: "Nieuwe alert maken",
    tr: "Yeni Uyarı Oluştur",
    id: "Buat Peringatan Baru",
    te: "కొత్త హెచ్చరికను సృష్టించండి",
    ta: "புதிய விழிப்பூட்டலை உருவாக்கவும்",
    bn: "নতুন সতর্কতা তৈরি করুন",
    mr: "नवीन अलर्ट तयार करा",
    vi: "Tạo thông báo mới",
    pl: "Utwórz powiadomienie",
    uk: "Створити сповіщення",
  },
  "common.applyNow": {
    en: "Apply Now",
    es: "Postularse Ahora",
    fr: "Postuler Maintenant",
    de: "Jetzt bewerben",
    zh: "立即申请",
    hi: "अभी आवेदन करें",
    ar: "قدم الآن",
    pt: "Candidatar-se",
    ja: "今すぐ応募",
    ru: "Откликнуться",
    ko: "지원하기",
    it: "Candidati Ora",
    nl: "Nu solliciteren",
    tr: "Hemen Başvur",
    id: "Lamar Sekarang",
    te: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    ta: "இப்போது விண்ணப்பிக்கவும்",
    bn: "এখনই আবেদন করুন",
    mr: "आता अर्ज करा",
    vi: "Ứng tuyển ngay",
    pl: "Aplikuj teraz",
    uk: "Подати заявку",
  },
  "common.save": {
    en: "Save",
    es: "Guardar",
    fr: "Enregistrer",
    de: "Speichern",
    zh: "保存",
    hi: "सहेजें",
    ar: "حفظ",
    pt: "Salvar",
    ja: "保存",
    ru: "Сохранить",
    ko: "저장",
    it: "Salva",
    nl: "Opslaan",
    tr: "Kaydet",
    id: "Simpan",
    te: "సేవ్ చేయండి",
    ta: "சேமிக்கவும்",
    bn: "সংরক্ষণ করুন",
    mr: "जतन करा",
    vi: "Lưu",
    pl: "Zapisz",
    uk: "Зберегти",
  },
  "common.saved": {
    en: "Saved",
    es: "Guardado",
    fr: "Enregistré",
    de: "Gespeichert",
    zh: "已保存",
    hi: "सहेजा गया",
    ar: "محفوظ",
    pt: "Salvo",
    ja: "保存済み",
    ru: "Сохранено",
    ko: "저장됨",
    it: "Salvato",
    nl: "Opgeslagen",
    tr: "Kaydedildi",
    id: "Tersimpan",
    te: "సేవ్ చేయబడింది",
    ta: "சேமிக்கப்பட்டது",
    bn: "সংরক্ষিত",
    mr: "जतन केले",
    vi: "Đã lưu",
    pl: "Zapisano",
    uk: "Збережено",
  },
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  supportedLanguages: LanguageOption[];
  currentLanguageOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem("moas_language");
      if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
        return saved as LanguageCode;
      }
    } catch {
      // ignore
    }
    return "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setCurrentLanguageState(lang);
    try {
      localStorage.setItem("moas_language", lang);
      // Set html lang attribute
      document.documentElement.lang = lang;
      if (lang === "ar") {
        document.documentElement.dir = "rtl";
      } else {
        document.documentElement.dir = "ltr";
      }
    } catch {
      // ignore
    }
  };

  useEffect(() => {
    document.documentElement.lang = currentLanguage;
    if (currentLanguage === "ar") {
      document.documentElement.dir = "rtl";
    } else {
      document.documentElement.dir = "ltr";
    }
  }, [currentLanguage]);

  const t = (key: string, fallback?: string): string => {
    const entry = translations[key];
    if (entry) {
      if (entry[currentLanguage]) {
        return entry[currentLanguage];
      }
      if (entry["en"]) {
        return entry["en"];
      }
    }
    return fallback || key;
  };

  const currentLanguageOption =
    SUPPORTED_LANGUAGES.find((l) => l.code === currentLanguage) ||
    SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
        currentLanguageOption,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
